# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oom15pfkoQYjBKKe_AFnXdmO8a8UFXdK
"""

# pip install streamlit

import streamlit as st

st.write("hello pradeep")

